#服务端设置
server:
  port: 8080
  #ip,域名都设置在address
  address: localhost
  tomcat:
    max-threads: 0
    uri-encoding: UTF-8

spring:
#HTTP编码设置
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
#配置thymeleaf模板路径
  mvc:
    view:
      prefix: /templates
      suffix: .html
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
#首先关闭默认的springsecurity的设置
security:
  basic:
    enabled: false





